### ISSUE TITLE
5ed Half-Elf parental choice not removing replaced skills (SCG)

### ISSUE THREAD

**Issue by adamdva** [BahamutDragon/pcgen#617]
I have a half-elf who I'm selecting the sun-elf parent. When I add the cantrip racial trait, the half-elf trait bonus is not removed.

**Comment by BahamutDragon** [comment]
Fixed mate.

**Comment by adamdva** [comment]
thanks for the quick response, see this in the log at start up now:

06:32:07.336 INFO main LanguageBundle:136 Initialising language bundle with
locale en_US.
06:32:23.567 INFO Thread-6 SourceFileLoader:560 Loading game 5e and sources
[Player's Handbook, Sword Coast Adventurer's Guide, Dungeon Master's Guide,
Elemental Evil Player's Companion].
06:32:23.572 SEVERE Thread-6 LstFileLoader:165
ERROR:file:/C:/Java/pcgen-homebrew/data/5e/wizards_of_the_coast/core/players_handbook/ph__datacontrols.lst
Exception type:java.io.FileNotFoundException
Message:C:\Java\pcgen-homebrew\data\5e\wizards_of_the_coast\core\players_handbook\ph__datacontrols.lst
(The system cannot find the file specified)
06:32:23.797 SEVERE Thread-6 Bonus:241 Can not parse
'PREFACT:1,ABILITIES,HALFELFSKILLVERSATILITY=TRUE': Unknown FACT in
PREFACT. Test was: HALFELFSKILLVERSATILITY=TRUE
pcgen.persistence.PersistenceLayerException: Can not parse
'PREFACT:1,ABILITIES,HALFELFSKILLVERSATILITY=TRUE': Unknown FACT in
PREFACT. Test was: HALFELFSKILLVERSATILITY=TRUE
at
pcgen.persistence.lst.prereq.PreParserFactory.parse(PreParserFactory.java:188)
at pcgen.core.bonus.Bonus.newBonus(Bonus.java:237)
at plugin.lsttokens.BonusLst.parseToken(BonusLst.java:82)
at plugin.lsttokens.BonusLst.parseToken(BonusLst.java:46)
at pcgen.rules.persistence.TokenSupport.processToken(TokenSupport.java:73)
at
pcgen.rules.context.LoadContextInst.processToken(LoadContextInst.java:328)
at
pcgen.rules.context.RuntimeLoadContext.processToken(RuntimeLoadContext.java:20)
at pcgen.persistence.lst.LstUtils.processToken(LstUtils.java:156)
at pcgen.persistence.lst.AbilityLoader.parseLine(AbilityLoader.java:80)
at pcgen.persistence.lst.AbilityLoader.parseLine(AbilityLoader.java:44)
at
pcgen.persistence.lst.LstObjectFileLoader.loadLstFile(LstObjectFileLoader.java:443)
at
pcgen.persistence.lst.LstObjectFileLoader.loadLstFiles(LstObjectFileLoader.java:113)
at
pcgen.persistence.SourceFileLoader.loadCampaigns(SourceFileLoader.java:656)
at
pcgen.persistence.SourceFileLoader.loadCampaigns(SourceFileLoader.java:507)
at pcgen.persistence.SourceFileLoader.execute(SourceFileLoader.java:248)
at pcgen.gui2.util.StatusWorker.construct(StatusWorker.java:74)
at pcgen.gui2.util.StatusWorker.construct(StatusWorker.java:42)
at pcgen.gui2.util.SwingWorker$1.run(SwingWorker.java:161)
at java.lang.Thread.run(Unknown Source)

06:32:23.797 SEVERE Thread-6 Bonus:242  (Source:
file:/C:/Java/pcgen-homebrew/data/5e/wizards_of_the_coast/core/players_handbook/ph_abilities.lst
)
06:32:23.799 LSTERROR Thread-6 LstUtils:164 BONUS was given invalid bonus:
VAR|HalfElfSkillVersatility|1|TYPE=Base|PREFACT:1,ABILITIES,HalfElfSkillVersatility=True
(Source:
file:/C:/Java/pcgen-homebrew/data/5e/wizards_of_the_coast/core/players_handbook/ph_abilities.lst
)
06:32:23.799 LSTERROR Thread-6 LstUtils:164 Illegal Token 'BONUS'
'VAR|HalfElfSkillVersatility|1|TYPE=Base|PREFACT:1,ABILITIES,HalfElfSkillVersatility=True'
for pcgen.core.Ability Racial Traits ~ Half-Elf in
file:/C:/Java/pcgen-homebrew/data/5e/wizards_of_the_coast/core/players_handbook/ph_abilities.lst
06:32:24.208 LSTERROR Thread-6 LstUtils:164 Illegal FACT subtoken
'HalfElfSkillVersatility' 'true' for Aquatic Swim Speed
06:32:24.208 LSTERROR Thread-6 LstUtils:164 Illegal Token 'FACT'
'HalfElfSkillVersatility|true' for pcgen.core.Ability Aquatic Swim Speed in
file:/C:/Java/pcgen-homebrew/data/5e/wizards_of_the_coast/campaign/forgotten_realms/sword_coast_adventurers_guide/scag_abilities.lst
06:32:24.342 LSTERROR Thread-6 LstUtils:164 Illegal FACT subtoken
'HalfElfSkillVersatility' 'true' for Keen Senses
06:32:24.342 LSTERROR Thread-6 LstUtils:164 Illegal Token 'FACT'
'HalfElfSkillVersatility|true' for pcgen.core.Ability Keen Senses in
file:/C:/Java/pcgen-homebrew/data/5e/wizards_of_the_coast/campaign/forgotten_realms/sword_coast_adventurers_guide/scag_abilities.lst
06:32:24.344 LSTERROR Thread-6 LstUtils:164 Illegal FACT subtoken
'HalfElfSkillVersatility' 'true' for Elf Weapon Training
06:32:24.344 LSTERROR Thread-6 LstUtils:164 Illegal Token 'FACT'
'HalfElfSkillVersatility|true' for pcgen.core.Ability Elf Weapon Training
in
file:/C:/Java/pcgen-homebrew/data/5e/wizards_of_the_coast/campaign/forgotten_realms/sword_coast_adventurers_guide/scag_abilities.lst
06:32:24.344 LSTERROR Thread-6 LstUtils:164 Illegal FACT subtoken
'HalfElfSkillVersatility' 'true' for Fleet of Foot
06:32:24.345 LSTERROR Thread-6 LstUtils:164 Illegal Token 'FACT'
'HalfElfSkillVersatility|true' for pcgen.core.Ability Fleet of Foot in
file:/C:/Java/pcgen-homebrew/data/5e/wizards_of_the_coast/campaign/forgotten_realms/sword_coast_adventurers_guide/scag_abilities.lst
06:32:24.345 LSTERROR Thread-6 LstUtils:164 Illegal FACT subtoken
'HalfElfSkillVersatility' 'true' for Mask of the Wild
06:32:24.345 LSTERROR Thread-6 LstUtils:164 Illegal Token 'FACT'
'HalfElfSkillVersatility|true' for pcgen.core.Ability Mask of the Wild in
file:/C:/Java/pcgen-homebrew/data/5e/wizards_of_the_coast/campaign/forgotten_realms/sword_coast_adventurers_guide/scag_abilities.lst
06:32:24.346 LSTERROR Thread-6 LstUtils:164 Illegal FACT subtoken
'HalfElfSkillVersatility' 'true' for Elf Weapon Training
06:32:24.346 LSTERROR Thread-6 LstUtils:164 Illegal Token 'FACT'
'HalfElfSkillVersatility|true' for pcgen.core.Ability Elf Weapon Training
in
file:/C:/Java/pcgen-homebrew/data/5e/wizards_of_the_coast/campaign/forgotten_realms/sword_coast_adventurers_guide/scag_abilities.lst
06:32:24.347 LSTERROR Thread-6 LstUtils:164 Illegal FACT subtoken
'HalfElfSkillVersatility' 'true' for Cantrip
06:32:24.347 LSTERROR Thread-6 LstUtils:164 Illegal Token 'FACT'
'HalfElfSkillVersatility|true' for pcgen.core.Ability Cantrip in
file:/C:/Java/pcgen-homebrew/data/5e/wizards_of_the_coast/campaign/forgotten_realms/sword_coast_adventurers_guide/scag_abilities.lst
06:32:24.347 LSTERROR Thread-6 LstUtils:164 Illegal FACT subtoken
'HalfElfSkillVersatility' 'true' for Drow Magic
06:32:24.347 LSTERROR Thread-6 LstUtils:164 Illegal Token 'FACT'
'HalfElfSkillVersatility|true' for pcgen.core.Ability Drow Magic in
file:/C:/Java/pcgen-homebrew/data/5e/wizards_of_the_coast/campaign/forgotten_realms/sword_coast_adventurers_guide/scag_abilities.lst

**Comment by adamdva** [comment]
looks like you forgot to add the ph__datacontrols.lst file.
happens all the time to me with git also.

**Comment by BahamutDragon** [comment]
Right. Fixed.
