### ISSUE TITLE
5e SCAG Rogue Swashbuckler, Rakish Audacity, not adding CHA modifier to misc initiative modifiers. 

### ISSUE THREAD

**Issue by meakman** [BahamutDragon/pcgen#624]
title
scag p. 136

**Comment by BahamutDragon** [comment]
Fixed mate.

**Comment by meakman** [comment]
Still isn't adding up for me. Initiative is only being calculated from dex modifier, no misc.
