### ISSUE TITLE
Some Tabaxi features do not load properly

### ISSUE THREAD

**Issue by jofo8948** [BahamutDragon/pcgen#897]
PCGen version: v6.08.00 RC4 (installed fresh today from .exe installer)
Branch: Confirmed with master & 6.08

Steps taken:
1. Create new character.
2. Set race to Tabaxi

Expected outcome:
* Racial Adjustments to ability scores set to DEX+2 & CHA+1
* Darkvision
* Proficient with Perception & Stealth skills
* Choice of Tabaxi additional language

Result:
None of above.
Climb speed seems to apply correctly.

Logfile: 
````
11:42:05.147 INFO Thread-8 SourceFileLoader:534 Loading game 5e and sources [Dungeons & Dragons 5e - Core Books, Volo's Guide to Monsters].
11:42:05.212 LSTERROR Thread-8 LstUtils:147 Could not get Reference Manufacturer for Category: Firbolg Race Trait (Source: file:/C:/Users/<redacted>/BahamutDragon/data/5e/wizards_of_the_coast/supplement/volos_guide_to_monsters/vgm_abilities.lst )
11:42:05.212 LSTERROR Thread-8 LstUtils:147 Failed in parsing typeStr: ABILITY Firbolg Race Trait|AUTOMATIC|TYPE=Base Firbolg Race Trait for pcgen.core.Ability Racial Traits ~ Firbolg
11:42:05.212 LSTERROR Thread-8 LstUtils:147 Illegal Token 'ABILITY' 'Firbolg Race Trait|AUTOMATIC|TYPE=Base Firbolg Race Trait' for pcgen.core.Ability Racial Traits ~ Firbolg in file:/C:/Users/<redacted>/BahamutDragon/data/5e/wizards_of_the_coast/supplement/volos_guide_to_monsters/vgm_abilities.lst
11:42:05.213 LSTERROR Thread-8 LstUtils:147 Could not get Reference Manufacturer for Category: Goliath Race Trait (Source: file:/C:/Users/<redacted>/BahamutDragon/data/5e/wizards_of_the_coast/supplement/volos_guide_to_monsters/vgm_abilities.lst )
11:42:05.214 LSTERROR Thread-8 LstUtils:147 Failed in parsing typeStr: ABILITY Goliath Race Trait|AUTOMATIC|TYPE=Base Goliath Race Trait for pcgen.core.Ability Racial Traits ~ Goliath
11:42:05.214 LSTERROR Thread-8 LstUtils:147 Illegal Token 'ABILITY' 'Goliath Race Trait|AUTOMATIC|TYPE=Base Goliath Race Trait' for pcgen.core.Ability Racial Traits ~ Goliath in file:/C:/Users/<redacted>/BahamutDragon/data/5e/wizards_of_the_coast/supplement/volos_guide_to_monsters/vgm_abilities.lst
11:42:05.215 LSTERROR Thread-8 LstUtils:147 Could not get Reference Manufacturer for Category: Kenku Race Trait (Source: file:/C:/Users/<redacted>/BahamutDragon/data/5e/wizards_of_the_coast/supplement/volos_guide_to_monsters/vgm_abilities.lst )
11:42:05.215 LSTERROR Thread-8 LstUtils:147 Failed in parsing typeStr: ABILITY Kenku Race Trait|AUTOMATIC|TYPE=Base Kenku Race Trait for pcgen.core.Ability Racial Traits ~ Kenku
11:42:05.222 LSTERROR Thread-8 LstUtils:147 Illegal Token 'ABILITY' 'Kenku Race Trait|AUTOMATIC|TYPE=Base Kenku Race Trait' for pcgen.core.Ability Racial Traits ~ Kenku in file:/C:/Users/<redacted>/BahamutDragon/data/5e/wizards_of_the_coast/supplement/volos_guide_to_monsters/vgm_abilities.lst
11:42:05.223 LSTERROR Thread-8 LstUtils:147 Could not get Reference Manufacturer for Category: Lizardfolk Race Trait (Source: file:/C:/Users/<redacted>/BahamutDragon/data/5e/wizards_of_the_coast/supplement/volos_guide_to_monsters/vgm_abilities.lst )
11:42:05.223 LSTERROR Thread-8 LstUtils:147 Failed in parsing typeStr: ABILITY Lizardfolk Race Trait|AUTOMATIC|TYPE=Base Lizardfolk Race Trait for pcgen.core.Ability Racial Traits ~ Lizardfolk
11:42:05.224 LSTERROR Thread-8 LstUtils:147 Illegal Token 'ABILITY' 'Lizardfolk Race Trait|AUTOMATIC|TYPE=Base Lizardfolk Race Trait' for pcgen.core.Ability Racial Traits ~ Lizardfolk in file:/C:/Users/<redacted>/BahamutDragon/data/5e/wizards_of_the_coast/supplement/volos_guide_to_monsters/vgm_abilities.lst
11:42:05.225 LSTERROR Thread-8 LstUtils:147 Could not get Reference Manufacturer for Category: Tabaxi Race Trait (Source: file:/C:/Users/<redacted>/BahamutDragon/data/5e/wizards_of_the_coast/supplement/volos_guide_to_monsters/vgm_abilities.lst )
11:42:05.225 LSTERROR Thread-8 LstUtils:147 Failed in parsing typeStr: ABILITY Tabaxi Race Trait|AUTOMATIC|TYPE=Base Tabaxi Race Trait for pcgen.core.Ability Racial Traits ~ Tabaxi
11:42:05.225 LSTERROR Thread-8 LstUtils:147 Illegal Token 'ABILITY' 'Tabaxi Race Trait|AUTOMATIC|TYPE=Base Tabaxi Race Trait' for pcgen.core.Ability Racial Traits ~ Tabaxi in file:/C:/Users/<redacted>/BahamutDragon/data/5e/wizards_of_the_coast/supplement/volos_guide_to_monsters/vgm_abilities.lst
11:42:05.226 LSTERROR Thread-8 LstUtils:147 Could not get Reference Manufacturer for Category: Triton Race Trait (Source: file:/C:/Users/<redacted>/BahamutDragon/data/5e/wizards_of_the_coast/supplement/volos_guide_to_monsters/vgm_abilities.lst )
11:42:05.227 LSTERROR Thread-8 LstUtils:147 Failed in parsing typeStr: ABILITY Triton Race Trait|AUTOMATIC|TYPE=Base Triton Race Trait for pcgen.core.Ability Racial Traits ~ Triton
11:42:05.227 LSTERROR Thread-8 LstUtils:147 Illegal Token 'ABILITY' 'Triton Race Trait|AUTOMATIC|TYPE=Base Triton Race Trait' for pcgen.core.Ability Racial Traits ~ Triton in file:/C:/Users/<redacted>/BahamutDragon/data/5e/wizards_of_the_coast/supplement/volos_guide_to_monsters/vgm_abilities.lst
11:42:05.228 LSTERROR Thread-8 LstUtils:147 Could not get Reference Manufacturer for Category: Bugbear Race Trait (Source: file:/C:/Users/<redacted>/BahamutDragon/data/5e/wizards_of_the_coast/supplement/volos_guide_to_monsters/vgm_abilities.lst )
11:42:05.229 LSTERROR Thread-8 LstUtils:147 Failed in parsing typeStr: ABILITY Bugbear Race Trait|AUTOMATIC|TYPE=Base Bugbear Race Trait for pcgen.core.Ability Racial Traits ~ PC Bugbear
11:42:05.229 LSTERROR Thread-8 LstUtils:147 Illegal Token 'ABILITY' 'Bugbear Race Trait|AUTOMATIC|TYPE=Base Bugbear Race Trait' for pcgen.core.Ability Racial Traits ~ PC Bugbear in file:/C:/Users/<redacted>/BahamutDragon/data/5e/wizards_of_the_coast/supplement/volos_guide_to_monsters/vgm_abilities.lst
11:42:05.230 LSTERROR Thread-8 LstUtils:147 Could not get Reference Manufacturer for Category: Hobgoblin Race Trait (Source: file:/C:/Users/<redacted>/BahamutDragon/data/5e/wizards_of_the_coast/supplement/volos_guide_to_monsters/vgm_abilities.lst )
11:42:05.230 LSTERROR Thread-8 LstUtils:147 Failed in parsing typeStr: ABILITY Hobgoblin Race Trait|AUTOMATIC|TYPE=Base Hobgoblin Race Trait for pcgen.core.Ability Racial Traits ~ PC Hobgoblin
11:42:05.231 LSTERROR Thread-8 LstUtils:147 Illegal Token 'ABILITY' 'Hobgoblin Race Trait|AUTOMATIC|TYPE=Base Hobgoblin Race Trait' for pcgen.core.Ability Racial Traits ~ PC Hobgoblin in file:/C:/Users/<redacted>/BahamutDragon/data/5e/wizards_of_the_coast/supplement/volos_guide_to_monsters/vgm_abilities.lst
11:42:05.232 LSTERROR Thread-8 LstUtils:147 Could not get Reference Manufacturer for Category: Kobold Race Trait (Source: file:/C:/Users/<redacted>/BahamutDragon/data/5e/wizards_of_the_coast/supplement/volos_guide_to_monsters/vgm_abilities.lst )
11:42:05.232 LSTERROR Thread-8 LstUtils:147 Failed in parsing typeStr: ABILITY Kobold Race Trait|AUTOMATIC|TYPE=Base Kobold Race Trait for pcgen.core.Ability Racial Traits ~ Kobold
11:42:05.232 LSTERROR Thread-8 LstUtils:147 Illegal Token 'ABILITY' 'Kobold Race Trait|AUTOMATIC|TYPE=Base Kobold Race Trait' for pcgen.core.Ability Racial Traits ~ Kobold in file:/C:/Users/<redacted>/BahamutDragon/data/5e/wizards_of_the_coast/supplement/volos_guide_to_monsters/vgm_abilities.lst
11:42:05.233 LSTERROR Thread-8 LstUtils:147 Could not get Reference Manufacturer for Category: Orc Race Trait (Source: file:/C:/Users/<redacted>/BahamutDragon/data/5e/wizards_of_the_coast/supplement/volos_guide_to_monsters/vgm_abilities.lst )
11:42:05.234 LSTERROR Thread-8 LstUtils:147 Failed in parsing typeStr: ABILITY Orc Race Trait|AUTOMATIC|Orc (VGM) ~ Ability Score Increase for pcgen.core.Ability Orc Base ~ VGM
11:42:05.234 LSTERROR Thread-8 LstUtils:147 Illegal Token 'ABILITY' 'Orc Race Trait|AUTOMATIC|Orc (VGM) ~ Ability Score Increase' for pcgen.core.Ability Orc Base ~ VGM in file:/C:/Users/<redacted>/BahamutDragon/data/5e/wizards_of_the_coast/supplement/volos_guide_to_monsters/vgm_abilities.lst
11:42:05.235 LSTERROR Thread-8 LstUtils:147 Could not get Reference Manufacturer for Category: Orc Race Trait (Source: file:/C:/Users/<redacted>/BahamutDragon/data/5e/wizards_of_the_coast/supplement/volos_guide_to_monsters/vgm_abilities.lst )
11:42:05.235 LSTERROR Thread-8 LstUtils:147 Failed in parsing typeStr: ABILITY Orc Race Trait|AUTOMATIC|Orc (VGM) ~ Darkvision for pcgen.core.Ability Orc Base ~ VGM
11:42:05.236 LSTERROR Thread-8 LstUtils:147 Illegal Token 'ABILITY' 'Orc Race Trait|AUTOMATIC|Orc (VGM) ~ Darkvision' for pcgen.core.Ability Orc Base ~ VGM in file:/C:/Users/<redacted>/BahamutDragon/data/5e/wizards_of_the_coast/supplement/volos_guide_to_monsters/vgm_abilities.lst
11:42:05.236 LSTERROR Thread-8 LstUtils:147 Could not get Reference Manufacturer for Category: Orc Race Trait (Source: file:/C:/Users/<redacted>/BahamutDragon/data/5e/wizards_of_the_coast/supplement/volos_guide_to_monsters/vgm_abilities.lst )
11:42:05.237 LSTERROR Thread-8 LstUtils:147 Failed in parsing typeStr: ABILITY Orc Race Trait|AUTOMATIC|Orc (VGM) ~ Aggressive for pcgen.core.Ability Orc Base ~ VGM
11:42:05.237 LSTERROR Thread-8 LstUtils:147 Illegal Token 'ABILITY' 'Orc Race Trait|AUTOMATIC|Orc (VGM) ~ Aggressive' for pcgen.core.Ability Orc Base ~ VGM in file:/C:/Users/<redacted>/BahamutDragon/data/5e/wizards_of_the_coast/supplement/volos_guide_to_monsters/vgm_abilities.lst
11:42:05.238 LSTERROR Thread-8 LstUtils:147 Could not get Reference Manufacturer for Category: Orc Race Trait (Source: file:/C:/Users/<redacted>/BahamutDragon/data/5e/wizards_of_the_coast/supplement/volos_guide_to_monsters/vgm_abilities.lst )
11:42:05.238 LSTERROR Thread-8 LstUtils:147 Failed in parsing typeStr: ABILITY Orc Race Trait|AUTOMATIC|Orc (VGM) ~ Menacing for pcgen.core.Ability Orc Base ~ VGM
11:42:05.238 LSTERROR Thread-8 LstUtils:147 Illegal Token 'ABILITY' 'Orc Race Trait|AUTOMATIC|Orc (VGM) ~ Menacing' for pcgen.core.Ability Orc Base ~ VGM in file:/C:/Users/<redacted>/BahamutDragon/data/5e/wizards_of_the_coast/supplement/volos_guide_to_monsters/vgm_abilities.lst
11:42:05.239 LSTERROR Thread-8 LstUtils:147 Could not get Reference Manufacturer for Category: Orc Race Trait (Source: file:/C:/Users/<redacted>/BahamutDragon/data/5e/wizards_of_the_coast/supplement/volos_guide_to_monsters/vgm_abilities.lst )
11:42:05.240 LSTERROR Thread-8 LstUtils:147 Failed in parsing typeStr: ABILITY Orc Race Trait|AUTOMATIC|Orc (VGM) ~ Powerful Build for pcgen.core.Ability Orc Base ~ VGM
11:42:05.240 LSTERROR Thread-8 LstUtils:147 Illegal Token 'ABILITY' 'Orc Race Trait|AUTOMATIC|Orc (VGM) ~ Powerful Build' for pcgen.core.Ability Orc Base ~ VGM in file:/C:/Users/<redacted>/BahamutDragon/data/5e/wizards_of_the_coast/supplement/volos_guide_to_monsters/vgm_abilities.lst
11:42:05.241 LSTERROR Thread-8 LstUtils:147 Could not get Reference Manufacturer for Category: Orc Race Trait (Source: file:/C:/Users/<redacted>/BahamutDragon/data/5e/wizards_of_the_coast/supplement/volos_guide_to_monsters/vgm_abilities.lst )
11:42:05.241 LSTERROR Thread-8 LstUtils:147 Failed in parsing typeStr: ABILITY Orc Race Trait|AUTOMATIC|Orc (VGM) ~ Languages for pcgen.core.Ability Orc Base ~ VGM
11:42:05.242 LSTERROR Thread-8 LstUtils:147 Illegal Token 'ABILITY' 'Orc Race Trait|AUTOMATIC|Orc (VGM) ~ Languages' for pcgen.core.Ability Orc Base ~ VGM in file:/C:/Users/<redacted>/BahamutDragon/data/5e/wizards_of_the_coast/supplement/volos_guide_to_monsters/vgm_abilities.lst
11:42:05.243 LSTERROR Thread-8 LstUtils:147 Could not get Reference Manufacturer for Category: Yuan-Ti Pureblood Race Trait (Source: file:/C:/Users/<redacted>/BahamutDragon/data/5e/wizards_of_the_coast/supplement/volos_guide_to_monsters/vgm_abilities.lst )
11:42:05.243 LSTERROR Thread-8 LstUtils:147 Failed in parsing typeStr: ABILITY Yuan-Ti Pureblood Race Trait|AUTOMATIC|TYPE=Base Yuan-Ti Pureblood Race Trait for pcgen.core.Ability Racial Traits ~ Yuan-Ti Pureblood
11:42:05.244 LSTERROR Thread-8 LstUtils:147 Illegal Token 'ABILITY' 'Yuan-Ti Pureblood Race Trait|AUTOMATIC|TYPE=Base Yuan-Ti Pureblood Race Trait' for pcgen.core.Ability Racial Traits ~ Yuan-Ti Pureblood in file:/C:/Users/<redacted>/BahamutDragon/data/5e/wizards_of_the_coast/supplement/volos_guide_to_monsters/vgm_abilities.lst
````

Speculation:
It seems from the logfile that there is a parse error for several Volo race's abilities, starting with Firbolg. Have not experimented with the others. Might be related to #882

**Comment by BahamutDragon** [comment]
Fixed log file errors

**Comment by BahamutDragon** [comment]
Fixing the root errors should resolve the remainder of the errors mate. None of the racial features were being applied before.

**Comment by jofo8948** [comment]
Pulled the update and tried again. 
Unfortunately, it still does not seem to apply the racial traits correctly.
Same errors. Tested out on a couple of other VGM races withb similar results. PHB races works fine.
Now using master branch on commit 13f0d6d3f8a4d00bc83e5a7a5226ec6e611fc0a1

Been trying to find the file format definitions again to try to fix it myself, but can's seem to find it anywhere anymore. Website is unhelpful and wiki seems to be down.
