### ISSUE TITLE
Human Racial adjustment is D&D 5e is not working

### ISSUE THREAD

**Issue by Deev87** [BahamutDragon/pcgen#977]
Hi,

Great work on this collection of source data.
I am quite new to pcgen but I managed to get everything working.

However I noticed something odd when trying to make a character for D&D 5e.
It seems that the racial bonusses for "Human" (+1 on everything) is not working.

Maybe its something i'm doing wrong or missing?

I'm using the latest version of PCgen (pcgen-6.08.00RC8) and I tried both the master branch and the 6.08 specific branch.

**Comment by BahamutDragon** [comment]
That should be working since the alternative is to gain a feat. I will take a look at it.

**Comment by BahamutDragon** [comment]
![image](https://user-images.githubusercontent.com/4307487/82130094-05aab080-977d-11ea-9d52-b17515431cd0.png)

![image](https://user-images.githubusercontent.com/4307487/82130106-19561700-977d-11ea-9a49-06563f4a2e59.png)

It works fine for me. See the above screenshots to see how to get the defaults.

**Comment by Deev87** [comment]
Hey,

It seems I forgot to do step 2 and 3, I only added "human" in the summary tab.
Still getting to know PCGen :S

Thanks for the help!
